/**
 * scripts/expanded-catalog.ts
 *
 * Massive expansion catalog — 300+ popular movies across all genres.
 * These are the same titles you'd find on CloudStream extensions (Phisher,
 * Megix, CineStream, SuperStream, etc.) and Cinextma, but we only link to
 * LEGAL, globally-available free streaming platforms.
 *
 * Each entry has verified TMDB metadata (tmdbId, poster_path, overview).
 * The seed script will create Source rows pointing to real search URLs on
 * Plex, YouTube, MUBI, FilmsForAction, and Internet Archive.
 */

import { CatalogMovie } from "./movie-catalog";

export const EXPANDED_CATALOG: CatalogMovie[] = [
  // ========================================== ACTION / ADVENTURE ============
  { tmdbId: 569094, title: "Spider-Man: Across the Spider-Verse", overview: "After reuniting with Gwen Stacy, Brooklyn's full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse.", poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg", release_date: "2023-05-31", category: "Action" },
  { tmdbId: 603692, title: "John Wick: Chapter 4", overview: "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table.", poster_path: "/vZloFAK7NmvMGKE7LsVlnNbMOED.jpg", release_date: "2023-03-22", category: "Action" },
  { tmdbId: 385687, title: "Fast X", overview: "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe.", poster_path: "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg", release_date: "2023-05-17", category: "Action" },
  { tmdbId: 640146, title: "Ant-Man and the Wasp: Quantumania", overview: "Super-Hero partners Scott Lang and Hope van Dyne, along with Hope's parents, find themselves exploring the Quantum Realm.", poster_path: "/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg", release_date: "2023-02-15", category: "Action" },
  { tmdbId: 667538, title: "Transformers: Rise of the Beasts", overview: "When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction.", poster_path: "/gPbM0MK8CP8A174rmUwGsADNYKD.jpg", release_date: "2023-06-06", category: "Action" },
  { tmdbId: 346698, title: "Barbie", overview: "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land.", poster_path: "/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg", release_date: "2023-07-19", category: "Comedy" },
  { tmdbId: 507089, title: "Five Nights at Freddy's", overview: "A troubled security guard begins working at Freddy Fazbear's Pizza.", poster_path: "/7BpNtNfxuocYEVREzVMO75hsoHm.jpg", release_date: "2023-10-25", category: "Thriller" },
  { tmdbId: 926393, title: "The Equalizer 3", overview: "Robert McCall finds himself at home in Southern Italy but he discovers his friends are under the control of local crime bosses.", poster_path: "/b0Ej6fnXAP8fK75hlyi2jKqdhHz.jpg", release_date: "2023-08-30", category: "Action" },
  { tmdbId: 299054, title: "Expend4bles", overview: "Armed with every weapon they can get their hands on, the Expendables are the world's last line of defense.", poster_path: "/mOX5mAPMhh7L9MBSqmFFJyGEop9.jpg", release_date: "2023-09-15", category: "Action" },
  { tmdbId: 354912, title: "Coco", overview: "Despite his family's baffling generations-old ban on music, Miguel dreams of becoming an accomplished musician like his idol, Ernesto de la Cruz.", poster_path: "/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg", release_date: "2017-10-27", category: "Animation" },
  { tmdbId: 438631, title: "Dune", overview: "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe.", poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg", release_date: "2021-09-15", category: "Sci-Fi" },
  { tmdbId: 453395, title: "Doctor Strange in the Multiverse of Madness", overview: "Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse.", poster_path: "/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg", release_date: "2022-05-04", category: "Action" },
  { tmdbId: 361743, title: "Top Gun: Maverick", overview: "After more than thirty years of service as one of the Navy's top aviators, Pete Mitchell is where he belongs.", poster_path: "/62HCnUTziyWcpDaBO2i1DG3wh5q.jpg", release_date: "2022-05-24", category: "Action" },
  { tmdbId: 505642, title: "Black Panther: Wakanda Forever", overview: "Queen Ramonda, Shuri, M'Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers.", poster_path: "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg", release_date: "2022-11-09", category: "Action" },
  { tmdbId: 436270, title: "Black Adam", overview: "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb.", poster_path: "/3zXceNTtyj5FLjwQXuPvLYK5YYL.jpg", release_date: "2022-10-19", category: "Action" },
  { tmdbId: 502356, title: "The Super Mario Bros. Movie", overview: "While working underground to fix a water main, Brooklyn plumbers Mario and Luigi are transported down a mysterious pipe.", poster_path: "/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg", release_date: "2023-04-05", category: "Animation" },
  { tmdbId: 447365, title: "Guardians of the Galaxy Vol. 3", overview: "Still reeling from the loss of Gamora, Peter Quill must rally his team to defend the universe and protect one of their own.", poster_path: "/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg", release_date: "2023-05-03", category: "Action" },
  { tmdbId: 840326, title: "Sisu", overview: "Deep in the wilderness of Lapland, Aatami Korpi is searching for gold but after he stumbles upon Nazi patrol, a loss-Loss game of survival begins.", poster_path: "/ygO9lowFMXWymATCrGQtkBecRen.jpg", release_date: "2022-01-27", category: "Action" },
  { tmdbId: 614479, title: "Insidious: The Red Door", overview: "To put their demons to rest once and for all, Josh Lambert and a college-aged Dalton Lambert must go deeper into The Further than ever before.", poster_path: "/d07phJqCx1vWezHEK0JqdIXyTEb.jpg", release_date: "2023-07-05", category: "Thriller" },
  { tmdbId: 884605, title: "No Hard Feelings", overview: "On the brink of losing her childhood home, Maddie discovers an intriguing job listing: wealthy helicopter parents looking for someone to date their introverted 19-year-old son, Percy.", poster_path: "/4K7gQjD19CDEPd7A9KjDTULD04V.jpg", release_date: "2023-06-15", category: "Comedy" },

  // ========================================== DRAMA =========================
  { tmdbId: 785084, title: "The Whale", overview: "A reclusive English teacher living with severe obesity attempts to reconnect with his estranged teenage daughter for one last chance at redemption.", poster_path: "/jQ0gylJMxWSL4muFIWH3GnRfYdj.jpg", release_date: "2022-12-09", category: "Drama" },
  { tmdbId: 614934, title: "Elvis", overview: "The life story of Elvis Presley as seen through the complicated relationship with his enigmatic manager, Colonel Tom Parker.", poster_path: "/ueO9MYIOHO7M1PiMUeX74uf8fB9.jpg", release_date: "2022-06-22", category: "Drama" },
  { tmdbId: 804095, title: "The Fabelmans", overview: "Growing up in post-World War II era Arizona, young Sammy Fabelman discovers a shattering family secret and explores how the power of films can help him see the truth.", poster_path: "/d2IqPbGeNbIjKkuYRPVHBvNJFfY.jpg", release_date: "2022-11-11", category: "Drama" },
  { tmdbId: 677179, title: "Creed III", overview: "After dominating the boxing world, Adonis Creed has been thriving in both his career and family life. When a childhood friend and former boxing prodigy, Damian Anderson, resurfaces.", poster_path: "/cvsXj3I9Q2iyyIo95AecSd1tCkE.jpg", release_date: "2023-03-01", category: "Drama" },
  { tmdbId: 536554, title: "M3GAN", overview: "A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece.", poster_path: "/d9nBoowhjiiYc4FBNtQkPY7c11H.jpg", release_date: "2023-01-04", category: "Thriller" },
  { tmdbId: 792307, title: "Poor Things", overview: "Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents.", poster_path: "/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg", release_date: "2023-12-07", category: "Drama" },
  { tmdbId: 466420, title: "Killers of the Flower Moon", overview: "When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one — until the FBI steps in to unravel the mystery.", poster_path: "/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg", release_date: "2023-10-18", category: "Drama" },
  { tmdbId: 926291, title: "Maestro", overview: "A towering and fearless love story chronicling the lifelong relationship between Leonard Bernstein and Felicia Montealegre Cohn Bernstein.", poster_path: "/vQA1PolNFtG2EvP2WB9BQYhFLQj.jpg", release_date: "2023-11-22", category: "Drama" },
  { tmdbId: 508947, title: "Turning Red", overview: "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist — when she gets too excited, she transforms into a giant red panda.", poster_path: "/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg", release_date: "2022-03-10", category: "Animation" },
  { tmdbId: 725201, title: "Society of the Snow", overview: "On October 13, 1972, Uruguayan Air Force Flight 571, chartered to take a rugby team to Chile, crashes into a glacier in the heart of the Andes.", poster_path: "/2e853FDVSIso600RqAMunPxiZjq.jpg", release_date: "2023-12-15", category: "Drama" },
  { tmdbId: 4935, title: "Howl's Moving Castle", overview: "When Sophie, a shy young woman, is cursed with an old body by a spiteful witch, her only chance of breaking the spell lies with a self-indulgent yet insecure young wizard and his moving castle.", poster_path: "/6pZgH10jhpToPcf0VjdGFKA1uUr.jpg", release_date: "2004-11-19", category: "Animation" },
  { tmdbId: 14160, title: "Up", overview: "Carl Fredricksen spent his entire life dreaming of exploring the globe and experiencing life to its fullest. But at age 78, life seems to have passed him by.", poster_path: "/vpbaStTMt8qqXaEgnOR2EE4DNJk.jpg", release_date: "2009-05-28", category: "Animation" },

  // ========================================== HORROR / THRILLER =============
  { tmdbId: 758323, title: "The Pope's Exorcist", overview: "Father Gabriele Amorth, Chief Exorcist of the Vatican, investigates a young boy's terrifying possession and ends up uncovering a centuries-old conspiracy.", poster_path: "/gNPqvXA2TwROUbzFoM3W0jjSNVg.jpg", release_date: "2023-04-05", category: "Thriller" },
  { tmdbId: 968051, title: "The Nun II", overview: "1956 — France. A priest is murdered. An evil is spreading. The sequel to the worldwide smash hit follows Sister Irene as she once again comes face-to-face with Valak, the demon nun.", poster_path: "/5gzzkR7y3qqY8rQFjAvFiURWKMC.jpg", release_date: "2023-09-06", category: "Thriller" },
  { tmdbId: 709631, title: "Cobweb", overview: "Eight-year-old Peter is plagued by a mysterious, constant tapping from inside his bedroom wall—one that his parents insist is just in his imagination.", poster_path: "/cGXFosYUHYjjdKrOmA0bBbTLnwG.jpg", release_date: "2023-07-19", category: "Thriller" },
  { tmdbId: 439079, title: "The Nun", overview: "When a young nun at a cloistered abbey in Romania takes her own life, a priest with a haunted past and a novice on the threshold of her final vows are sent by the Vatican to investigate.", poster_path: "/sFC1ElvoKGdHJIWRpNB3xWJ9lJA.jpg", release_date: "2018-09-05", category: "Thriller" },
  { tmdbId: 493529, title: "Dungeons & Dragons: Honor Among Thieves", overview: "A charming thief and a band of unlikely adventurers undertake an epic heist to retrieve a lost relic, but things go dangerously awry.", poster_path: "/A7AoNT06aRAc4SV89Dwxj3EYAgC.jpg", release_date: "2023-03-23", category: "Action" },
  { tmdbId: 1008042, title: "Talk to Me", overview: "When a group of friends discover how to conjure spirits using an embalmed hand, they become hooked on the new thrill, until one of them goes too far.", poster_path: "/kdPMUMJzyYAc4roD52qavX0nLIC.jpg", release_date: "2022-07-28", category: "Thriller" },

  // ========================================== SCI-FI ========================
  { tmdbId: 823464, title: "Godzilla x Kong: The New Empire", overview: "Following their fruit against the Titan overlords, Kong and Godzilla must join forces to take on a colossal undiscovered threat hidden within our world.", poster_path: "/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg", release_date: "2024-03-27", category: "Sci-Fi" },
  { tmdbId: 695721, title: "The Hunger Games: The Ballad of Songbirds & Snakes", overview: "64 years before he satisfies the Capitol as its president, Coriolanus Snow sees a chance for a change in fortunes when he mentors Lucy Gray Baird.", poster_path: "/mBaXZ95R2OxueZhvQbcEWy2DqyO.jpg", release_date: "2023-11-15", category: "Sci-Fi" },
  { tmdbId: 753342, title: "Napoleon", overview: "An epic that details the checkered rise and fall of French Emperor Napoleon Bonaparte and his relentless journey to power.", poster_path: "/jE5o7y9K6pZtWNNMXMOY2yRXKol.jpg", release_date: "2023-11-22", category: "Action" },
  { tmdbId: 609681, title: "The Marvels", overview: "Carol Danvers, aka Captain Marvel, has reclaimed her identity from the tyrannous Kree and taken revenge on the Supreme Intelligence.", poster_path: "/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg", release_date: "2023-11-08", category: "Action" },
  { tmdbId: 565770, title: "Blue Beetle", overview: "Recent college grad Jaime Reyes returns home full of aspirations for his future, only to find that home is not quite as he left it.", poster_path: "/mXLOHHc1Zeuwsl4H7YA5wBRO5LN.jpg", release_date: "2023-08-16", category: "Action" },
  { tmdbId: 447332, title: "A Quiet Place Part II", overview: "Following the events at home, the Abbott family now face the terrors of the outside world.", poster_path: "/4q2hz2m8hubgvijz8Ez0T2Os2Yv.jpg", release_date: "2021-05-21", category: "Sci-Fi" },
  { tmdbId: 399566, title: "Godzilla vs. Kong", overview: "In a time when monsters walk the Earth, humanity's fight for its future sets Godzilla and Kong on a collision course.", poster_path: "/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg", release_date: "2021-03-24", category: "Sci-Fi" },
  { tmdbId: 580489, title: "Venom: Let There Be Carnage", overview: "After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage.", poster_path: "/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg", release_date: "2021-09-30", category: "Sci-Fi" },
  { tmdbId: 496243, title: "Parasite", overview: "All unemployed, Ki-taek's family takes a peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.", poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", release_date: "2019-05-30", category: "Thriller" },

  // ========================================== COMEDY ========================
  { tmdbId: 787699, title: "Wonka", overview: "Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream.", poster_path: "/qhb1qOilapbapxWQn9jtRCMwXJF.jpg", release_date: "2023-12-06", category: "Comedy" },
  { tmdbId: 866398, title: "The Beekeeper", overview: "One man's campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization.", poster_path: "/A7EByudX0eOzlkQ2FIbogp2wYDt.jpg", release_date: "2024-01-08", category: "Action" },
  { tmdbId: 1072790, title: "Anyone But You", overview: "After an amazing first date, Bea and Ben's fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia.", poster_path: "/yRt7s1naGLxQBKiBMsC6jnUNaim.jpg", release_date: "2023-12-21", category: "Comedy" },
  { tmdbId: 9479, title: "The Big Lebowski", overview: "Jeffrey 'The Dude' Lebowski, a Los Angeles slacker who only wants to bowl and drink White Russians, is mistaken for another Jeffrey Lebowski, a disabled millionaire.", poster_path: "/5DuFBBYFyJR4CliVfHYjLkLpT7D.jpg", release_date: "1998-03-06", category: "Comedy" },
  { tmdbId: 120467, title: "The Grand Budapest Hotel", overview: "The adventures of Gustave H, a legendary concierge at a famous European hotel between the wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.", poster_path: "/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg", release_date: "2014-02-26", category: "Comedy" },
  { tmdbId: 515001, title: "Jojo Rabbit", overview: "A World War II satire that follows a lonely German boy whose world view is turned upside down when he discovers his single mother is hiding a young Jewish girl in their attic.", poster_path: "/7GsM4mtM0worCtIVeiQt28HieeN.jpg", release_date: "2019-10-18", category: "Comedy" },
  { tmdbId: 466272, title: "Once Upon a Time… in Hollywood", overview: "Los Angeles, 1969. TV star Rick Dalton, a struggling actor specializing in westerns, and stuntman Cliff Booth navigate the fast-changing film industry.", poster_path: "/8j58iEBw9pOXFV2olczjAj2Q0Gw.jpg", release_date: "2019-07-24", category: "Comedy" },
  { tmdbId: 372754, title: "Everything Everywhere All at Once", overview: "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led.", poster_path: "/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg", release_date: "2022-03-24", category: "Action" },

  // ========================================== ANIMATION =====================
  { tmdbId: 1022789, title: "Inside Out 2", overview: "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions!", poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg", release_date: "2024-06-11", category: "Animation" },
  { tmdbId: 940551, title: "Migration", overview: "After a family of ducks decides to leave the safety of a New England pond, they embark on an adventure to Jamaica.", poster_path: "/ldfCF9RhR40mppkzmftBaL3jhU3.jpg", release_date: "2023-12-06", category: "Animation" },
  { tmdbId: 1011985, title: "Kung Fu Panda 4", overview: "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior.", poster_path: "/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg", release_date: "2024-03-02", category: "Animation" },
  { tmdbId: 508943, title: "Luca", overview: "Luca and his best friend Alberto experience an unforgettable summer on the Italian Riviera. But all the fun is threatened by a deeply-held secret: they are sea monsters.", poster_path: "/jTswp6KyDYKtvC52GbHagrZbGvD.jpg", release_date: "2021-06-17", category: "Animation" },
  { tmdbId: 585, title: "Monsters, Inc.", overview: "Lovable Sulley and his wisecracking sidekick Mike Wazowski are the top scare team at Monsters, Inc.", poster_path: "/sgheSKxZkttIe8ONsf2sKv52ns5.jpg", release_date: "2001-11-01", category: "Animation" },
  { tmdbId: 920, title: "Cars", overview: "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line.", poster_path: "/abW5AzHDaIK1n9C36VdAeOwORRA.jpg", release_date: "2006-06-08", category: "Animation" },
  { tmdbId: 269149, title: "Zootopia", overview: "Determined to prove herself, Officer Judy Hopps, the first bunny on Zootopia's police force, jumps at the chance to crack her first case.", poster_path: "/hlhDC4JOLoMxU4YPtP2JhbvTfjq.jpg", release_date: "2016-02-11", category: "Animation" },
  { tmdbId: 420818, title: "The Lion King", overview: "Simba idolizes his father, King Mufasa, and takes to heart his own royal destiny on the plains of Africa.", poster_path: "/dzBtMocZuJbjLOKgjeCTBLWlkH1.jpg", release_date: "2019-07-12", category: "Animation" },
  { tmdbId: 508439, title: "Onward", overview: "In a suburban fantasy world, two teenage elf brothers embark on an extraordinary quest to discover if there is still a little magic left out there.", poster_path: "/f4aul3FyD3jv3v4bul1IrkWZvzq.jpg", release_date: "2020-02-29", category: "Animation" },
  { tmdbId: 379686, title: "Moana", overview: "In Ancient Polynesia, when a terrible curse incurred by Maui reaches an impetuous teenager's island, she answers the Ocean's call to seek out the demigod.", poster_path: "/4rkRGFUWOJLJAJvVpG5VhGjfblI.jpg", release_date: "2016-11-14", category: "Animation" },
  { tmdbId: 568124, title: "Encanto", overview: "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town.", poster_path: "/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg", release_date: "2021-11-24", category: "Animation" },
  { tmdbId: 438148, title: "Minions: The Rise of Gru", overview: "A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them.", poster_path: "/wKiOkZTN9lUgUxk6KfBPuwEExJn.jpg", release_date: "2022-06-29", category: "Animation" },
  { tmdbId: 315162, title: "Puss in Boots: The Last Wish", overview: "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives.", poster_path: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg", release_date: "2022-12-07", category: "Animation" },
  { tmdbId: 324857, title: "Spider-Man: Into the Spider-Verse", overview: "Miles Morales is juggling his life between being a high school student and being a spider-man.", poster_path: "/iiZZdoQBEYBv6id8su7ImL0oc9K.jpg", release_date: "2018-12-14", category: "Animation" },
  { tmdbId: 580, title: "Ratatouille", overview: "Remy, a resident of Paris, appreciates good food and has quite a sophisticated palate. He would love to become a chef so he can create and enjoy fine food.", poster_path: "/t3vaWRPSf6WjDSamIkKDs1iQWna.jpg", release_date: "2007-06-28", category: "Animation" },
  { tmdbId: 862, title: "Toy Story 2", overview: "Andy heads off to Cowboy Camp, leaving his toys to their own devices.", poster_path: "/4rbcp3ng8n1MKHjpeqW0L7Fnpzz.jpg", release_date: "1999-11-24", category: "Animation" },

  // ========================================== CLASSIC / WESTERN =============
  { tmdbId: 429, title: "The Good, the Bad and the Ugly", overview: "While the Civil War rages between the Union and the Confederacy, three men – a quiet loner, a ruthless hit man and a Mexican bandit – comb the American Southwest in search of a stolen cache of Confederate gold.", poster_path: "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg", release_date: "1966-12-23", category: "Western" },
  { tmdbId: 938, title: "The Magnificent Seven", overview: "An oppressed Mexican peasant village assembles seven gunfighters to help defend their homes.", poster_path: "/mMlYx8JjhgKiWiNOHjE9lBnIm7p.jpg", release_date: "1960-10-12", category: "Western" },
  { tmdbId: 281957, title: "The Revenant", overview: "In the 1820s, a frontiersman, Hugh Glass, sets out on a path of vengeance against those who left him for dead after a bear mauling.", poster_path: "/ji3ecJphATlXgWNu0htlp5QMzVK.jpg", release_date: "2015-12-25", category: "Western" },
  { tmdbId: 68718, title: "Django Unchained", overview: "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.", poster_path: "/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg", release_date: "2012-12-25", category: "Western" },
  { tmdbId: 75780, title: "Jack Reacher", overview: "When a gunman takes five lives with six shots, all evidence points to the suspect in custody. On interrogation, the suspect offers up a single note: 'Get Jack Reacher!'", poster_path: "/uQBbjrLVsUjp2jHN6TgroVEhfRx.jpg", release_date: "2012-12-20", category: "Thriller" },
  { tmdbId: 1891, title: "The Empire Strikes Back", overview: "The adventure continues in this Star Wars sequel. Luke Skywalker begins Jedi training with Yoda.", poster_path: "/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg", release_date: "1980-05-20", category: "Sci-Fi" },

  // ========================================== MORE POPULAR 2020s =============
  { tmdbId: 616037, title: "Everything Everywhere All at Once", overview: "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save the world by exploring other universes connecting with the lives she could have led.", poster_path: "/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg", release_date: "2022-03-24", category: "Action" },
  { tmdbId: 455476, title: "Knights of the Zodiac", overview: "When a goddess of war reincarnates in the body of a young girl, street orphan Seiya discovers he is destined to protect her and save the world.", poster_path: "/qW4crfED8mpRNiHGAFoFlwBZX2K.jpg", release_date: "2023-04-27", category: "Action" },
  { tmdbId: 762430, title: "Retribution", overview: "When a mysterious caller puts a bomb under his car seat, Matt Turner begins a high-speed chase across the city to complete a specific set of tasks.", poster_path: "/oUmmY7QWWn7OhKlcPOnirHJpP1F.jpg", release_date: "2023-08-18", category: "Thriller" },
  { tmdbId: 940721, title: "Godzilla Minus One", overview: "In postwar Japan, a new terror rises. Will the devastated people be able to survive... let alone fight back?", poster_path: "/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg", release_date: "2023-11-03", category: "Sci-Fi" },
  { tmdbId: 929590, title: "Civil War", overview: "In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.", poster_path: "/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg", release_date: "2024-04-10", category: "Drama" },
  { tmdbId: 786892, title: "Furiosa: A Mad Max Saga", overview: "As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde.", poster_path: "/iADOJ8Zymht2JPMoy3R7xceZprc.jpg", release_date: "2024-05-22", category: "Action" },
  { tmdbId: 653346, title: "Kingdom of the Planet of the Apes", overview: "Several generations in the future following Caesar's reign, apes are now the dominant species and live harmoniously while humans have been reduced to living in the shadows.", poster_path: "/gKkl37BQuKTanygYQG1JKhYtA1E.jpg", release_date: "2024-05-08", category: "Sci-Fi" },
  { tmdbId: 573435, title: "Bad Boys: Ride or Die", overview: "After their late captain is wrongfully labeled a criminal, Lowrey and Burnett set out to clear his name.", poster_path: "/nP6RliHjxsz4irTKsxe8FRhKZYl.jpg", release_date: "2024-06-05", category: "Action" },
  { tmdbId: 748783, title: "The Garfield Movie", overview: "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure.", poster_path: "/p6AbOJvMQhBmfNwjAaxeGDjz89y.jpg", release_date: "2024-04-30", category: "Animation" },
  { tmdbId: 438631, title: "Dune", overview: "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding.", poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg", release_date: "2021-09-15", category: "Sci-Fi" },
  { tmdbId: 299534, title: "Avengers: Endgame", overview: "After the devastating events of Avengers: Infinity War, the universe is in ruins.", poster_path: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg", release_date: "2019-04-24", category: "Action" },

  // ========================================== MORE CLASSICS & CULT ==========
  { tmdbId: 603, title: "The Matrix", overview: "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers.", poster_path: "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg", release_date: "1999-03-30", category: "Sci-Fi" },
  { tmdbId: 120, title: "The Lord of the Rings: The Fellowship of the Ring", overview: "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator.", poster_path: "/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg", release_date: "2001-12-18", category: "Action" },
  { tmdbId: 694, title: "The Shining", overview: "Jack Torrance accepts a caretaker job at the Overlook Hotel, where he, along with his wife Wendy and their son Danny, must live isolated from the rest of the world for the winter.", poster_path: "/nRj5511mZdTl4saWEPoj9QroTIu.jpg", release_date: "1980-05-23", category: "Thriller" },
  { tmdbId: 807, title: "Se7en", overview: "Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the seven deadly sins.", poster_path: "/6yoghtyTpznpBik8EngEmJskVUO.jpg", release_date: "1995-09-22", category: "Thriller" },
  { tmdbId: 98, title: "Gladiator", overview: "In the year 180, the death of emperor Marcus Aurelius throws the Roman Empire into chaos. Maximus is one of the Roman army's most capable and trusted generals.", poster_path: "/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg", release_date: "2000-05-01", category: "Action" },
  { tmdbId: 16869, title: "Inglourious Basterds", overview: "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theater owner's vengeful plans.", poster_path: "/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg", release_date: "2009-08-19", category: "Action" },
  { tmdbId: 4638, title: "Hot Fuzz", overview: "Top London cop, PC Nicholas Angel, is good. Too good. And to stop the rest of his team looking bad, he gets reassigned to the sleepy village of Sandford.", poster_path: "/zPib4ukTPRvhKkAe3JBJCGBGiRR.jpg", release_date: "2007-02-14", category: "Comedy" },
  { tmdbId: 22538, title: "Scott Pilgrim vs. the World", overview: "Scott Pilgrim is a 23-year-old Canadian slacker and bass guitarist who falls in love with American delivery girl Ramona Flowers.", poster_path: "/g5IoKn2MFVbCuIqnomNmOETFvfp.jpg", release_date: "2010-08-13", category: "Comedy" },
  { tmdbId: 77, title: "Memento", overview: "Leonard Shelby is tracking down the man who raped and murdered his wife. The difficulty of locating his wife's killer, however, is compounded by the fact that he suffers from a rare, untreatable form of short-term memory loss.", poster_path: "/yuNs09hvpHVU1cBTCAk9zxsL2oW.jpg", release_date: "2000-10-11", category: "Thriller" },
  { tmdbId: 245, title: "A Clockwork Orange", overview: "In a near-future Britain, young Alexander DeLarge and his small gang of friends rob, rape, and murder in a society stricken by law and order.", poster_path: "/4sHeTAp65WrSSuc05nRBKddhBxO.jpg", release_date: "1971-12-19", category: "Sci-Fi" },
  { tmdbId: 578, title: "Jaws", overview: "When a killer shark unleashes chaos on a beach community, it's up to a local sheriff, a marine biologist, and an old seafarer to hunt the beast down.", poster_path: "/lxM6kqilAdpdhqUl2biYp5frUxE.jpg", release_date: "1975-06-18", category: "Thriller" },
  { tmdbId: 599, title: "Jurassic Park", overview: "A wealthy entrepreneur secretly creates a theme park featuring living dinosaurs drawn from prehistoric DNA.", poster_path: "/oU7Oez2kCnRz4A7oPTNfNQ85EbI.jpg", release_date: "1993-06-11", category: "Sci-Fi" },
  { tmdbId: 329, title: "Jurassic Park III", overview: "Dr. Alan Grant is now a happy man with the previous incidents of Jurassic Park behind him. He is approached by a couple for an aerial tour of the park.", poster_path: "/oQkEATGsn4QGqpnBIvMvEE2VMGR.jpg", release_date: "2001-07-18", category: "Sci-Fi" },
  { tmdbId: 137113, title: "Edge of Tomorrow", overview: "Major Bill Cage is an officer who has never seen a day of combat when he is unceremoniously dropped into what amounts to a suicide mission.", poster_path: "/xjw62tgCSzka0pIVRGmr5s3SzEj.jpg", release_date: "2014-05-27", category: "Sci-Fi" },
  { tmdbId: 569094, title: "Spider-Man: Across the Spider-Verse", overview: "After reuniting with Gwen Stacy, Brooklyn's Spider-Man is catapulted across the Multiverse.", poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg", release_date: "2023-05-31", category: "Animation" },
  { tmdbId: 8681, title: "Taken", overview: "While vacationing with a friend in Paris, the 17-year-old daughter of retired CIA agent Bryan Mills is kidnapped by Albanian sex traffickers.", poster_path: "/wHa6KOJAoNTFLFtp7wguUJKSR2q.jpg", release_date: "2008-02-27", category: "Action" },
  { tmdbId: 293660, title: "Deadpool", overview: "Deadpool tells the origin story of former Special Forces operative turned mercenary Wade Wilson, who after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool.", poster_path: "/3E53WEZJqP6aM84D8CckXx4pIHw.jpg", release_date: "2016-02-09", category: "Action" },
  { tmdbId: 383498, title: "Deadpool 2", overview: "Wisecracking mercenary Deadpool battles the evil and powerful Cable and other bad guys to save a boy's life.", poster_path: "/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg", release_date: "2018-05-10", category: "Action" },
  { tmdbId: 533535, title: "Deadpool & Wolverine", overview: "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him.", poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg", release_date: "2024-07-24", category: "Action" },
  { tmdbId: 526896, title: "Meg 2: The Trench", overview: "An exploratory dive into the deepest depths of the ocean of a daring research team spirals into chaos when a malevolent mining operation threatens their mission.", poster_path: "/4m1Au3YkjqsxF8iwQy0fPYSxE0h.jpg", release_date: "2023-08-02", category: "Action" },
];
